#!/usr/bin/env python

import argparse
import sys
import os
import json
from subprocess import check_output
import re

def parse_args():
  pass

def main(args=None):

    print("generating your commit...")
    # git lab commit url
    commit_base_url = "https://git.fligno.com/wetext/v2/wetext-mobile/-/commit/"

    commit_hash = check_output(['git', 'rev-parse', '--verify', 'HEAD']).strip()
    __location__ = os.path.realpath(
        os.path.join(os.getcwd(), os.path.dirname(__file__)))

    data = {}
    with open(os.path.join(__location__, 'data.json')) as json_file:
        data = json.load(json_file)
        details = data['hris_data']['details'];
        commit_message = data['commit_data']['content']
        data['hris_data']['details'] = details + "[%s](%s%s);" % (commit_message, commit_base_url, commit_hash)

        # revert commit_data content to ''
        data['commit_data']['content'] = ''

    with open(os.path.join(__location__, 'data.json'), 'w') as outfile:
        json.dump(data, outfile)

    with open(os.path.join(__location__, 'message.txt'), 'w') as outfile:
        json.dump(data['hris_data']['details'], outfile)

if __name__ == "__main__":
  args = parse_args()
  main(args)
