#!/usr/bin/env python

import argparse
import sys, os, re
from subprocess import check_output


def parse_args():
    pass


def main(args=None):
    pass


if __name__ == "__main__":
    args = parse_args()
    main(args)
